export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1c1b1b",
        "on-primary-container": "#ff8371",
        "inverse-on-surface": "#f1f1f1",
        "on-surface-variant": "#5a413d",
        "outline-variant": "#e2bfb9",
        "inverse-primary": "#ffb4a8",
        "on-tertiary-container": "#94a0ff",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary": "#00137f",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#410000",
        "secondary": "#5f5e5e",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container-high": "#e8e8e8",
        "surface": "#f9f9f9",
        "error-container": "#ffdad6",
        "surface-variant": "#e2e2e2",
        "on-background": "#1b1b1b",
        "tertiary-container": "#0021b9",
        "background": "#f9f9f9",
        "on-error": "#ffffff",
        "on-surface": "#1b1b1b",
        "tertiary-fixed": "#dfe0ff",
        "surface-bright": "#f9f9f9",
        "primary-fixed": "#ffdad4",
        "tertiary-fixed-dim": "#bcc2ff",
        "on-tertiary-fixed": "#000c61",
        "secondary-container": "#e2dfde",
        "surface-container-highest": "#e2e2e2",
        "surface-container-low": "#f3f3f3",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#8f0f07",
        "outline": "#8e706c",
        "surface-container": "#eeeeee",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#1830c2",
        "surface-dim": "#dadada",
        "primary-container": "#800000",
        "surface-tint": "#b22b1d",
        "on-secondary-fixed-variant": "#474746",
        "on-secondary-container": "#636262",
        "primary-fixed-dim": "#ffb4a8",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "primary": "#570000",
        "inverse-surface": "#303030"
      },
      fontFamily: {
        "headline": ["Noto Serif"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
